### ISSUE TITLE
Directory not initialized with correct name.

### ISSUE THREAD

**Issue by amarlearning** [amarlearning/Github-Sectory#1]
Directory not initialized with correct name while downloading nested sub-direcotries

**Comment by yetanothernerdk** [comment]
This issue is still up? 😕 Unable to create it at my side. Any specific directory you tried to access?

**Comment by amarlearning** [comment]
@yetanothernerdk Try out this link: [https://github.com/jhu-ep-coursera/fullstack-course5/tree/master/examples/Lecture37](link)
In this case, folder name should be `Lecture37` but instead folder created with name `example`.

**Comment by iankur** [comment]
I have created a PR for resolving this issue.
