### ISSUE TITLE
Error formatting of error message if the Internet is not working.

### ISSUE THREAD

**Issue by amarlearning** [amarlearning/github-sectory#3]
Error formatting of error message if the Internet is not working.

**Comment by iankur** [comment]
@amarlearning I have created a PR for the same. Please let me know if there is some issue. #4

**Comment by amarlearning** [comment]
@iankur LGTM :100:

**Comment by shreab373** [comment]
is this issue still available?

**Comment by amarlearning** [comment]
@shreab373 Before you proceed to take this issue, please read [this](https://github.com/amarlearning/Github-Sectory/pull/4).

Let me know if you need any help.

**Comment by shreab373** [comment]
read it, what exactly needs to be done here?

**Comment by amarlearning** [comment]
Thanks to @iankur for resolving this issue too much extent! :smile: 

> It may happen that the connection goes away in the middle of the process. This may prevent from making further connections which are taken care by the above case. It may also happen that the connection was established to get a socket and then the connection goes away. This may leave the socket waiting indefinitely. So I added a timeout parameter which helps us to detect the above case with another exception. **However, there is a problem with this approach. Downloading large files may not be possible if it takes longer than the timeout**.

@shreab373 You can resolve this issue "**However, there is a problem with this approach. Downloading large files may not be possible if it takes longer than the timeout**"

Here the timeout is set to 30 secs if any file takes longer it will be canceled!

**Comment by sk364** [comment]
@amarlearning @iankur  I could reproduce the issue with the timeout parameter raising the exception when the internet connection went down, but I wasn't able to reproduce the issue dealing with download of large files with a timeout parameter. It continues to download for more than the timeout value.

**Comment by theharshitgarg** [comment]
@amarlearning @iankur is this issue still valid. If yes, can you please explain in more detail

**Comment by amarlearning** [comment]
@sk364 @theharshitgarg by timeout error I meant that if someone's internet connection is slow and the size of the page that we are trying to get is large then, in that case, it might take more than `30secs` to get the data from the page. 

this issue is all about this problem and sorry for the delay.

https://github.com/amarlearning/Github-Sectory/blob/582c936d50a663d6859571c93ede4e2660f2986a/github-sectory#L98

**Comment by amarlearning** [comment]
@saurabh259 yes, this issue is open.

**Comment by swapniljha001** [comment]
Please close this issue if it has been resolved, else it can create a lot of confusion.
