### ISSUE TITLE
Progress bar for ongoing download

### ISSUE THREAD

**Issue by iankur** [amarlearning/Github-Sectory#5]
I think there should be a dynamic progress bar to show the ongoing download status to the users. Something similar to what we find while using shell in linux.

**Comment by amarlearning** [comment]
@iankur Interesting, sounds good!
Do you want to work on this ?

**Comment by iankur** [comment]
Yeah, I will take it up.

**Comment by amarlearning** [comment]
Looking forward to your PR :smile:
