### ISSUE TITLE
Preserve commit history for files?

### ISSUE THREAD

**Issue by brylie** [amarlearning/Github-Sectory#7]
We are considering moving *part* of an open source project into a different project, and would like to preserve the commit history. That way the original authors still get attribution.

Does this tool preserve the commit history for files downloaded within the subfolder?

**Comment by amarlearning** [comment]
@brylie no, this tool does not preserve git commit history. It just downloads the subdirectory of any github repository locally.

**Comment by brylie** [comment]
OK, thanks.
