### ISSUE TITLE
Add Test cases

### ISSUE THREAD

**Issue by jayvdb** [amarlearning/github-sectory#9]
It would be useful to have some basic smoke tests.  I would like to create a package for openSUSE, but without any tests it isnt maintainable.

Also would be good to move the majority of the logic into a package, so the script is a thin wrapper, as that makes it more testable, and also the logic becomes re-usable.

**Comment by amarlearning** [comment]
@jayvdb I agree with you, if you want you can take up this issue. :smiley:

**Comment by elaynelemos** [comment]
> @jayvdb I agree with you, if you want you can take up this as an issue.

Hey! Still active?

**Comment by jayvdb** [comment]
Sorry, I have a full plate.  I'd like to use this as a package, as a dependency in my own library.  Until you restructure it to be a package, this is not useful for me.

And I dont want to restructure it - the blame/ownership of the new lines in the new files should be the primary author, not me.

**Comment by amarlearning** [comment]
@jayvdb @elaynelemos I will do it I have some time these days if you guys are not taking.

**Comment by fstavela** [comment]
It looks like this one is still unresolved. Can I take it?

**Comment by fstavela** [comment]
@jayvdb @amarlearning  Because you wanted to restructure this I guess you were more interested in system tests for the CLI then in unit tests. I wrote some basic ones in PR https://github.com/amarlearning/github-sectory/pull/14. Is this acceptable, or did you have a different idea?

**Comment by jayvdb** [comment]
It is a great start.

The refactor can be a separate task.
